name: Audit
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      minlevel: critical
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Audit
        id: audit
        run: npm audit --audit-level $minlevel
